schemas_root: genai_graph.ekg.schema
paths:
  rainbow_md: '${paths.ekg_data}/rainbow/md/'
  rainbow_json: '${paths.ekg_data}/rainbow/json/'
  rainbow_pdf: '${paths.ekg_data}/rainbow/pdf/'
  rainbow_ppt: '${paths.ekg_data}/rainbow/ppt/'
  add_json: '${paths.ekg_data}/arch_doc/json/'
  stratnav_db: '${paths.ekg_data}/stratnav'
kg_build:
  llms:
    default: gpt_oss120@openrouter
  embeddings:
    default: ada_002@openrouter



kg_configs:
  one_rainbow:
    graphs:
      - factory: 'genai_graph.ekg.schema.rainbow_review.ReviewedOpportunityGraph'
        data_root: '${paths.rainbow_json}'
        include:
          - '*CNES*TMA*VENUS*'
        exclude:
          - fake/*
        recursive: true
        file_embedding:
          metadata:
            - Opportunity.opportunity_id
            - Customer.name
  crm_export:
    graphs:
      - factory: '${schemas_root}.crm_export.CrmExtractGraph'
        files:
          - '${paths.ekg_data}/crm_export/report1750429630460_SHORTEN.xlsx'
        pd_read_parameters: {}
  one_rainbow_with_db:
    graphs:
      - factory: '${schemas_root}.rainbow_review.ReviewedOpportunityGraph'
        data_root: '${paths.rainbow_json}'
        include:
          - '*CNES*TMA*VENUS*'
        exclude:
          - fake/*
        recursive: true
      - factory: '${schemas_root}.crm_export.CrmExtractGraph'
        files:
          - '${paths.ekg_data}/crm_export/report1750429630460_SHORTEN.xlsx'
        pd_read_parameters: {}
        filter_by_existing:
          node_label: Opportunity
          property: opportunity_id
  rainbow_add_crm:
    graphs:
      - factory: 'genai_graph.ekg.schema.rainbow_review.ReviewedOpportunityGraph'
        data_root: '${paths.rainbow_json}'
        include:
          - '*CNES*'
        exclude:
          - fake/*
        recursive: true
      - factory: 'genai_graph.ekg.schema.architecture_doc.ArchitectureDocumentGraph'
        data_root: '${paths.add_json}'
        include:
          - '*CNES*'
        exclude:
          - fake/*
        recursive: true
      - factory: '${schemas_root}.crm_export.CrmExtractGraph'
        files:
          - '${paths.ekg_data}/crm_export/report1750429630460_SHORTEN.xlsx'
        pd_read_parameters: {}
        filter_by_existing:
          node_label: Opportunity
          property: opportunity_id
  several_rainbow:
    graphs:
      - factory: 'genai_graph.ekg.schema.rainbow_review.ReviewedOpportunityGraph'
        data_root: '${paths.rainbow_json}'
        include:
          - '*.json'
        recursive: true
  stratnav_subset:
    graphs:
      - factory: 'genai_graph.ekg.schema.stratnav.StratnavGraph'
        neo4j_export_file: '${paths.stratnav_db}/subset/sn-subset200.jsonl'
        embeddings:
          - field: L3.descriptionEmbedding
            model: ada_002@openrouter

  stratnav_subset_rainbow_crm:
    import:
      - rainbow_add_crm
      - stratnav_subset

  learned_stratnav_subset_rainbow_crm:
    import:
      - stratnav_subset_rainbow_crm
    graphs:
      - factory: 'genai_graph.ekg.schema.learned_graph.L3TechApproachMatcher'
        similarities:
          - relationship: POSSIBLE_OFFERING
            from: TechnicalApproach.architecture
            to: L3.description
            iterate_over: from
            threshold: 0.8
            top_k: 5
            combiner: first