
schemas_root: genai_graph.ekg.schema

paths:
  rainbow_md : ${paths.ekg_data}/rainbow/md/
  rainbow_json : ${paths.ekg_data}/rainbow/json/
  rainbow_pdf : ${paths.ekg_data}/rainbow/pdf/
  rainbow_ppt : ${paths.ekg_data}/rainbow/ppt/
  add_json : ${paths.ekg_data}/arch_doc/json/
  stratnav_db : ${paths.ekg_data}/stratnav

kg_configs:
  one_rainbow:
    graphs:
      - factory: genai_graph.ekg.schema.rainbow_review:ReviewedOpportunityGraph
        data_root: ${paths.rainbow_json}
        include: 
          - "*_CNES_TMA_VENUS_VIP_PEPS_THEIA_MUSCATE*"
        exclude: 
          - "fake/*"
        recursive: true
        file_embedding:
          metadata: ["Opportunity.opportunity_id","Customer.name"]

  crm_export:  
    graphs:
      - factory: "${schemas_root}.crm_export:CrmExtractGraph"
        db_dsn: sqlite:///${paths.data_root}/ekg/crm_extract.db
        files:
          - ${paths.ekg_data}/crm_export/report1750429630460_SHORTEN.xlsx
        pd_read_parameters: {} 

  one_rainbow_with_db:
    import:
      - crm_export
    graphs:
      - factory: "${schemas_root}.rainbow_review:ReviewedOpportunityGraph"
        data_root: ${paths.rainbow_json}
        include: 
          - "*_CNES_TMA_VENUS_VIP_PEPS_THEIA_MUSCATE*"
        exclude: 
          - "fake/*"
        recursive: true

  rainbow_add_crm:
    import:
      - crm_export
    graphs:
      - factory: genai_graph.ekg.schema.rainbow_review:ReviewedOpportunityGraph
        data_root: ${paths.rainbow_json}
        include: 
          - "*_CNES_*"
        recursive: true
      - factory: genai_graph.ekg.schema.architecture_doc:ArchitectureDocumentGraph
        data_root: ${paths.add_json}
        include: 
          - "*_CNES_*"
        recursive: true 

  several_rainbow:
    graphs:
      - factory: genai_graph.ekg.schema.rainbow_review:ReviewedOpportunityGraph
        data_root: ${paths.rainbow_json}
        include: 
          - "*.json"
        recursive: true
  
  stratnav_subset:
    graphs:
      - factory: genai_graph.ekg.schema.stratnav:StratnavGraph 
        neo4j_export_file: ${paths.stratnav_db}/subset/sn-subset200.jsonl

  stratnav_subset_rainbow_crm:
    import:
      - rainbow_add_crm
      - stratnav_subset

  # stratnav:
  #   graphs:
  #     - factory: genai_graph.ekg.schema.stratnav:StratnavGraph 
  #       neo4j_export_file: ${paths.stratnav_db}/26-01-2018/sn-v3-q4-2026-01-28.jsonl


